# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5545049470b8dd6055f97014ec378ea5829ce80ac93c7137ddd23974945773093854db7c6241ce17b59fee1fa0f9407acc794f7f4670df33401783fc3304c7bf

test:
  secret_key_base: 0025089026bdaf8fc28599c26dab396f636dd03ccc8aa44b5f980bdba4f32f7ab883b002b1d57f94b09bb3fd1fde93cc37fd65abb81ceeee23c1bec196610877

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
